add missing number implementation in Rust
mre/the-coding-interview pull request #113
Opened 2019-04-17 13:27 UTC by jxs

2019-12-02 08:09 UTC, Fleshgrinder requested changes

2019-12-02 08:09 UTC, Fleshgrinder commented on problems/missing-number/missing-number.rs
> +  println!("missing number: {}", missing_number(&[1,3,5,7,11]).unwrap());
This gives 9 but 2, 4, 6, 8, 9, and 10 are missing. The input is actually incorrect. I believe that all solutions suffer from a misinterpretation of the problem.

2023-10-13 11:00 UTC, jxs reviewed
sorry didn't see this notification until now. Updated!

2023-10-17 21:35 UTC, mre commented
The additional tests were nice. Why did you remove them? 🤔

2023-10-20 09:55 UTC, jxs commented
> The additional tests were nice. Why did you remove them? 🤔

cause the after reading https://github.com/mre/the-coding-interview/pull/113#discussion_r352460062 and following the new implementation from other solutions most of the tests were failing. Added back the passing ones and made the implementation only accept `usize`'s as some tests were for negative ranges.

2023-10-30 14:23 UTC, merged

2023-10-30 14:24 UTC, mre commented
Thanks for your contribution @jxs and sorry that it took very long to get merged.